# Generated by Django 5.0.6 on 2024-06-29 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='overview',
            field=models.TextField(default='', max_length=500),
        ),
    ]
