# Generated by Django 5.0.6 on 2024-06-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_blog_content_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content_3',
            field=models.TextField(blank=True, max_length=5000),
        ),
    ]
